//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: mistyswap_common.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
#if canImport(LibMobileCoinCommon)
import LibMobileCoinCommon
#endif
import NIO
import SwiftProtobuf


/// Usage: instantiate `MistyswapCommon_MistyswapCommonApiClient`, then call methods of this protocol to make API calls.
public protocol MistyswapCommon_MistyswapCommonApiClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: MistyswapCommon_MistyswapCommonApiClientInterceptorFactoryProtocol? { get }

  func getInfo(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, MistyswapCommon_GetInfoResponse>
}

extension MistyswapCommon_MistyswapCommonApiClientProtocol {
  public var serviceName: String {
    return "mistyswap_common.MistyswapCommonApi"
  }

  //// Get information about this mistyswap instance.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getInfo(
    _ request: SwiftProtobuf.Google_Protobuf_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, MistyswapCommon_GetInfoResponse> {
    return self.makeUnaryCall(
      path: "/mistyswap_common.MistyswapCommonApi/GetInfo",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInfoInterceptors() ?? []
    )
  }
}

public protocol MistyswapCommon_MistyswapCommonApiClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getInfo'.
  func makeGetInfoInterceptors() -> [ClientInterceptor<SwiftProtobuf.Google_Protobuf_Empty, MistyswapCommon_GetInfoResponse>]
}

public final class MistyswapCommon_MistyswapCommonApiClient: MistyswapCommon_MistyswapCommonApiClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: MistyswapCommon_MistyswapCommonApiClientInterceptorFactoryProtocol?

  /// Creates a client for the mistyswap_common.MistyswapCommonApi service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: MistyswapCommon_MistyswapCommonApiClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

